name: HTML to Markdown

on:
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '*/5 * * * *'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./cronjobs

jobs:
  html-to-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Convert HTML to Markdown
        env:
          USERS_INFO_URL: ${{ secrets.USERS_INFO_URL }}
          USERS_INFO_API_KEY: ${{ secrets.USERS_INFO_API_KEY }}
          WEBPAGE_SUMMARIZER_API_URL: ${{ secrets.WEBPAGE_SUMMARIZER_API_URL }}
          WEBPAGE_SUMMARIZER_API_KEY: ${{ secrets.WEBPAGE_SUMMARIZER_API_KEY }}
        run: |
          #!/bin/bash
          set -e
          WEBPAGE_SUMMARIZER_API_URLS=$(curl -s -L ${USERS_INFO_URL}?apiKey=${USERS_INFO_API_KEY} -H "Content-Type: application/json" | jq -r '.urls[]')
          if [ -z "$WEBPAGE_SUMMARIZER_API_URLS" ]; then
            WEBPAGE_SUMMARIZER_API_URLS=(${WEBPAGE_SUMMARIZER_API_URL})
          fi
          for target_url in ${WEBPAGE_SUMMARIZER_API_URLS}; do
            url_list=$(curl -s -L ${target_url}?apiKey=${WEBPAGE_SUMMARIZER_API_KEY} -H "Content-Type: application/json" | jq -r '.urls[]')
            for url in ${url_list}; do
              html=$(curl -s -L ${url})
              tmpfile=$(mktemp)
              echo "${html}" > "${tmpfile}"
              node ./dist/main.js "${url}" "${tmpfile}" "${target_url}"
              rm "${tmpfile}"
            done
          done
